language: r
cache: packages
warnings_are_errors: false

dist: bionic
osx_image: xcode11

r:
  - oldrel
  - release
  - devel
  
os:
  - linux
  - osx

brew_packages:
  - llvm

r_packages:
  - covr
  - lintr
  - bit64
  - nanotime
  - testthat
  - data.table

after_success:
  - test $TRAVIS_OS_NAME == "linux" &&
    travis_wait Rscript -e 'library(covr); codecov(quiet = FALSE)'

env:
  global:
    - PKG_CXXFLAGS="-O3 -Wall -pedantic"
