language: r
cache: packages
dist: bionic
warnings_are_errors: false

r:
  - release
os:
  - osx

jobs:
  exclude:
  - r: devel
    os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install --force llvm &&
    export PATH="/usr/local/opt/llvm/bin:$PATH" &&
    export LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib" &&
    export CPPFLAGS="-I/usr/local/opt/llvm/include"; fi

r_packages:
  - covr
  - lintr
  - bit64
  - nanotime
  - testthat
  - data.table

after_success:
  - test $TRAVIS_OS_NAME == "linux" &&
    travis_wait Rscript -e 'library(covr); codecov(quiet = FALSE)'

env:
  global:
    - PKG_CXXFLAGS="-O3 -Wall -pedantic"
